Create ingress TLS secret based on provider
projectsyn/component-keycloak pull request #115
Opened 2022-02-15 21:48 UTC by mhutter

For the Ingress certificate, `ingress.tls.provider` is relevant for
determining whether or not to create the secret from Vault.

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [ ] Link this PR to related issues or PRs.

2022-02-16 09:44 UTC, anothertobi approved these changes

2022-02-16 11:01 UTC, anothertobi requested changes
Since this is a breaking change, it would make sense to include a small version upgrade documentation.

2022-03-28 10:01 UTC, ccremer commented
@mhutter @anothertobi You might want to include/combine the upgrade documentation in #119 and release the PRs together.

2022-05-24 15:46 UTC, mhutter commented
Discussed with @megian -- will close this PR for now and revisit the topic once #128 and the subsequent migration to Quarkus is done

2022-05-24 15:46 UTC, mhutter commented
Discussed with @megian -- will close this PR for now and revisit the topic once #128 and the subsequent migration to Quarkus is done

2022-05-24 15:47 UTC, closed without merging