Deprecate "passthrough" TLS termination mode
projectsyn/component-keycloak pull request #99
Opened 2021-11-25 14:50 UTC by mhutter

"Passthrough" was originally implemented on the bases that there is no
easy way to
- provide a cert that works with OpenShift Routers in reencrypt modes
- use self-signed certificates with long expiry dates

Hence this commit removes it from the chart, instead making the whole
component MUCH simpler.

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [x] Link this PR to related issues or PRs.

2021-11-25 15:27 UTC, ccremer requested changes
I think we have misunderstanding of the word "Deprecation".

As outlined in https://syn.tools/commodore/reference/deprecation-policy.html and https://syn.tools/syn/references/review-guide.html a deprecated feature shall still work for a while and only require a minor, non-breaking change. What you did in this PR is completely skip the deprecation, but directly removed support for a feature.

I'm not against the change overall, but please reword the PR and documentation so that there's no mention of deprecation, but rather "removed support/feature" or similar.

2021-11-25 15:48 UTC, ccremer approved these changes
I lost the overview which modes and combinations we now support :see_no_evil: 
I trust that you know what you do :)

Just some styling suggestions (one-line-per-sentence)

2021-11-25 15:48 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/upgrade-5.x-to-6.x.adoc
> +* Removal of "passthrough" TLS termination mode. "reencrypt" is used instead.
```suggestion
* Removal of `passthrough` TLS termination mode.
  `reencrypt` is used instead.
```

2021-11-25 15:48 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/upgrade-5.x-to-6.x.adoc
> +. Remove `tls.termination`. It is not supported anymore.
```suggestion
. Remove `tls.termination`.
  It is not supported anymore.
```

2021-11-25 15:48 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/upgrade-5.x-to-6.x.adoc
> +. Remove `tls.termination`. It's not supported anymore.
```suggestion
. Remove `tls.termination`.
  It's not supported anymore.
```

2021-11-25 16:24 UTC, ccremer commented
@megian IIRC you have this feature activated in one of the cluster. Is this something you can live with?

2021-11-26 07:50 UTC, megian commented
> @megian IIRC you have this feature activated in one of the cluster. Is this something you can live with?

Since I had to implement something for the re-encrypt cert (It's a EKS cluster) and don't have the time for. I will try to override it or do a fork of the component for this customer.

2021-11-26 08:18 UTC, ccremer requested changes
@megian can you and @mhutter discuss further how to proceed here?
We in Tarazed think that a fork within our own company should be avoided...
Probably we shouldn't merge this PR yet.

2021-11-30 09:27 UTC, mhutter commented
@megian My idea was that I migrate the existing passthrough setup (it's a single one) after v6 of this component is released, since it was my understanding that there is no requirement to HAVE a passthrough setup at all

I agree @ccremer that a fork should be avoided at all cost :)

2021-11-30 12:37 UTC, megian commented
@mhutter The original idea was to have a end to end encryption to mitigate any man in the middle attacks. Keycloak would be the first I would try to attack. Reencrypt is less secure, as it does open up the potential the ingress controller has some flaws. From a security view - in my opinion -, the highest possible security configuration should be the default of a security component. This is the reason, why I'm not so convinced to prune this option out of the component.

However configuring a manual certificate for the internal cert is a broken concept from my point of view. As it's insecure to have in example a 10 year certificate (especially for a security component like Keycloak) and we currently also don't have any monitoring implemented, for those certificates. 

OpenShift might use https://docs.openshift.com/container-platform/4.9/security/certificate_types_descriptions/service-ca-certificates.html, but my knowledge this is not available on native K8s. https://cert-manager.io/docs/configuration/selfsigned/ might do it.

Manually handling certificates is the worst option. Cryptic and painful to manage. Will check, if there is a better option.

2021-12-02 09:57 UTC, mhutter commented
Then I misunderstood the reasons why passthrough was used in the first place, sorry for that.

However since we cannot use certmanager for Passthrough because of keycloak, we can agree that "passthrough" only supports Vault as a certificate source, is that correct?

2021-12-03 10:15 UTC, closed without merging